# Generated by Django 4.2.20 on 2025-05-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_razorpaypayment_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='customer_phone',
        ),
    ]
