# Generated by Django 4.2.20 on 2025-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='dive_locations/')),
                ('boat_ride_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('depth_range_min', models.PositiveIntegerField(help_text='Minimum depth in meters')),
                ('depth_range_max', models.PositiveIntegerField(help_text='Maximum depth in meters')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dive Location',
                'verbose_name_plural': 'Dive Locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_featured', 'is_active'], name='mainSite_di_is_feat_ce1c7f_idx')],
            },
        ),
    ]
