# Generated by Django 4.2.20 on 2025-05-18 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mainSite.event'),
        ),
        migrations.AddIndex(
            model_name='razorpaypayment',
            index=models.Index(fields=['event', 'booking_date'], name='mainSite_ra_event_i_46d90d_idx'),
        ),
    ]
