# Generated by Django 4.2.20 on 2025-05-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_razorpaypayment_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.RenameField(
            model_name='newslettersubscription',
            old_name='created_at',
            new_name='subscribed_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='updated_at',
        ),
    ]
