# Generated by Django 4.2.20 on 2025-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0011_instructorbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorbooking',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='instructorbooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='instructorbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='instructorbooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructorbooking',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructorbooking',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructorbooking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
