# Generated by Django 4.2.20 on 2025-05-18 14:39

from django.db import migrations
import mainSite.utils.imagekit_field


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0013_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.AlterField(
            model_name='divelocation',
            name='featured_image',
            field=mainSite.utils.imagekit_field.ImageKitField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='featured_image',
            field=mainSite.utils.imagekit_field.ImageKitField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=mainSite.utils.imagekit_field.ImageKitField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=mainSite.utils.imagekit_field.ImageKitField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=mainSite.utils.imagekit_field.ImageKitField(max_length=500),
        ),
    ]
