# Generated by Django 4.2.20 on 2025-05-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0014_delete_instructor_alter_divelocation_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divingservice',
            name='duration',
            field=models.PositiveIntegerField(help_text='Base duration in minutes'),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='included_items',
            field=models.TextField(blank=True, help_text='Base items included in the service, one per line'),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='Base price or starting price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='requirements',
            field=models.TextField(blank=True, help_text='Base requirements for this service, one per line'),
        ),
        migrations.CreateModel(
            name='CourseVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('included_items', models.TextField(blank=True, help_text='Items specific to this variation')),
                ('requirements', models.TextField(blank=True, help_text='Requirements specific to this variation')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='mainSite.divingservice')),
            ],
            options={
                'verbose_name': 'Course Variation',
                'verbose_name_plural': 'Course Variations',
                'ordering': ['order', 'price'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='mainSite_co_service_b25d64_idx'), models.Index(fields=['order', 'price'], name='mainSite_co_order_064918_idx')],
            },
        ),
    ]
