# Generated by Django 4.2.20 on 2025-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0016_divingservice_variations_delete_coursevariation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divingservice',
            options={'ordering': ['name'], 'verbose_name': 'Diving Service', 'verbose_name_plural': 'Diving Services'},
        ),
        migrations.RemoveIndex(
            model_name='divingservice',
            name='mainSite_di_categor_b1c9cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='divingservice',
            name='mainSite_di_is_feat_555215_idx',
        ),
        migrations.RemoveIndex(
            model_name='divingservice',
            name='mainSite_di_difficu_55b2ed_idx',
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='max_participants',
            field=models.PositiveIntegerField(default=4, help_text='Maximum number of participants'),
        ),
        migrations.AlterField(
            model_name='divingservice',
            name='variations',
            field=models.JSONField(blank=True, help_text='Course variations stored as JSON. Format: [{"id": "str", "name": "str", "price": float, "duration": int, "max_participants": int}]', null=True),
        ),
    ]
